### ISSUE TITLE
runtime: out of memory due to JSON marshal/unmarshal

### ISSUE THREAD

**Issue by heidi-ann** [heidi-ann/ios#13]
There are various memory issues with JSON marshal/unmarshal. At the moment, we do this either in a strange verbose manner or has been replicated by a placeholder to prevent errors like this:

```
~/go/bin/server -id=0
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x5ddf0c, 0x16)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc440500000, 0x20000000, 0xa00001f700, 0x6d64b8)
	/usr/local/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0x6bda40, 0x20000000, 0x34e3f)
	/usr/local/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0x6bda40, 0x10000, 0x0)
	/usr/local/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0x6bda40, 0x10000, 0x0)
	/usr/local/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).allocStack(0x6bda40, 0x10000, 0x40f0fc)
	/usr/local/go/src/runtime/mheap.go:597 +0x62
runtime.stackalloc(0x20000000, 0xc41fd57b00, 0x100, 0x40, 0x2000, 0x7f0d9b218710)
	/usr/local/go/src/runtime/stack.go:395 +0x2ed
runtime.copystack(0xc4200001a0, 0x20000000, 0x1)
	/usr/local/go/src/runtime/stack.go:839 +0x83
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1070 +0x370
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:366 +0x7f

goroutine 1 [copystack]:
encoding/json.(*decodeState).object(0xc42550ee10, 0x5aa960, 0xc4254fd668, 0x16)
	/usr/local/go/src/encoding/json/decode.go:557 fp=0xc430500488 sp=0xc430500480
encoding/json.(*decodeState).value(0xc42550ee10, 0x5aa960, 0xc4254fd668, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430500508 sp=0xc430500488
encoding/json.(*decodeState).unmarshal(0xc42550ee10, 0x5aa960, 0xc4254fd668, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430500580 sp=0xc430500508
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd668, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc4305005c8 sp=0xc430500580
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd650, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430500610 sp=0xc4305005c8
encoding/json.(*decodeState).object(0xc42550ed20, 0x5aa960, 0xc4254fd650, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc4305008a0 sp=0xc430500610
encoding/json.(*decodeState).value(0xc42550ed20, 0x5aa960, 0xc4254fd650, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430500920 sp=0xc4305008a0
encoding/json.(*decodeState).unmarshal(0xc42550ed20, 0x5aa960, 0xc4254fd650, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430500998 sp=0xc430500920
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd650, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc4305009e0 sp=0xc430500998
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd638, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430500a28 sp=0xc4305009e0
encoding/json.(*decodeState).object(0xc42550ec30, 0x5aa960, 0xc4254fd638, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430500cb8 sp=0xc430500a28
encoding/json.(*decodeState).value(0xc42550ec30, 0x5aa960, 0xc4254fd638, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430500d38 sp=0xc430500cb8
encoding/json.(*decodeState).unmarshal(0xc42550ec30, 0x5aa960, 0xc4254fd638, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430500db0 sp=0xc430500d38
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd638, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430500df8 sp=0xc430500db0
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd620, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430500e40 sp=0xc430500df8
encoding/json.(*decodeState).object(0xc42550eb40, 0x5aa960, 0xc4254fd620, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc4305010d0 sp=0xc430500e40
encoding/json.(*decodeState).value(0xc42550eb40, 0x5aa960, 0xc4254fd620, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430501150 sp=0xc4305010d0
encoding/json.(*decodeState).unmarshal(0xc42550eb40, 0x5aa960, 0xc4254fd620, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc4305011c8 sp=0xc430501150
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd620, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430501210 sp=0xc4305011c8
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd608, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430501258 sp=0xc430501210
encoding/json.(*decodeState).object(0xc42550ea50, 0x5aa960, 0xc4254fd608, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc4305014e8 sp=0xc430501258
encoding/json.(*decodeState).value(0xc42550ea50, 0x5aa960, 0xc4254fd608, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430501568 sp=0xc4305014e8
encoding/json.(*decodeState).unmarshal(0xc42550ea50, 0x5aa960, 0xc4254fd608, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc4305015e0 sp=0xc430501568
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd608, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430501628 sp=0xc4305015e0
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd5f0, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430501670 sp=0xc430501628
encoding/json.(*decodeState).object(0xc42550e960, 0x5aa960, 0xc4254fd5f0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430501900 sp=0xc430501670
encoding/json.(*decodeState).value(0xc42550e960, 0x5aa960, 0xc4254fd5f0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430501980 sp=0xc430501900
encoding/json.(*decodeState).unmarshal(0xc42550e960, 0x5aa960, 0xc4254fd5f0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc4305019f8 sp=0xc430501980
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd5f0, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430501a40 sp=0xc4305019f8
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd5d8, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430501a88 sp=0xc430501a40
encoding/json.(*decodeState).object(0xc42550e870, 0x5aa960, 0xc4254fd5d8, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430501d18 sp=0xc430501a88
encoding/json.(*decodeState).value(0xc42550e870, 0x5aa960, 0xc4254fd5d8, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430501d98 sp=0xc430501d18
encoding/json.(*decodeState).unmarshal(0xc42550e870, 0x5aa960, 0xc4254fd5d8, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430501e10 sp=0xc430501d98
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd5d8, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430501e58 sp=0xc430501e10
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd5c0, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430501ea0 sp=0xc430501e58
encoding/json.(*decodeState).object(0xc42550e780, 0x5aa960, 0xc4254fd5c0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430502130 sp=0xc430501ea0
encoding/json.(*decodeState).value(0xc42550e780, 0x5aa960, 0xc4254fd5c0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc4305021b0 sp=0xc430502130
encoding/json.(*decodeState).unmarshal(0xc42550e780, 0x5aa960, 0xc4254fd5c0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430502228 sp=0xc4305021b0
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd5c0, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430502270 sp=0xc430502228
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd5a8, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc4305022b8 sp=0xc430502270
encoding/json.(*decodeState).object(0xc42550e690, 0x5aa960, 0xc4254fd5a8, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430502548 sp=0xc4305022b8
encoding/json.(*decodeState).value(0xc42550e690, 0x5aa960, 0xc4254fd5a8, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc4305025c8 sp=0xc430502548
encoding/json.(*decodeState).unmarshal(0xc42550e690, 0x5aa960, 0xc4254fd5a8, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430502640 sp=0xc4305025c8
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd5a8, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430502688 sp=0xc430502640
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd590, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc4305026d0 sp=0xc430502688
encoding/json.(*decodeState).object(0xc42550e5a0, 0x5aa960, 0xc4254fd590, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430502960 sp=0xc4305026d0
encoding/json.(*decodeState).value(0xc42550e5a0, 0x5aa960, 0xc4254fd590, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc4305029e0 sp=0xc430502960
encoding/json.(*decodeState).unmarshal(0xc42550e5a0, 0x5aa960, 0xc4254fd590, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430502a58 sp=0xc4305029e0
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd590, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430502aa0 sp=0xc430502a58
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd578, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430502ae8 sp=0xc430502aa0
encoding/json.(*decodeState).object(0xc42550e4b0, 0x5aa960, 0xc4254fd578, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430502d78 sp=0xc430502ae8
encoding/json.(*decodeState).value(0xc42550e4b0, 0x5aa960, 0xc4254fd578, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430502df8 sp=0xc430502d78
encoding/json.(*decodeState).unmarshal(0xc42550e4b0, 0x5aa960, 0xc4254fd578, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430502e70 sp=0xc430502df8
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd578, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430502eb8 sp=0xc430502e70
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd560, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430502f00 sp=0xc430502eb8
encoding/json.(*decodeState).object(0xc42550e3c0, 0x5aa960, 0xc4254fd560, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430503190 sp=0xc430502f00
encoding/json.(*decodeState).value(0xc42550e3c0, 0x5aa960, 0xc4254fd560, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430503210 sp=0xc430503190
encoding/json.(*decodeState).unmarshal(0xc42550e3c0, 0x5aa960, 0xc4254fd560, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430503288 sp=0xc430503210
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd560, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc4305032d0 sp=0xc430503288
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd548, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430503318 sp=0xc4305032d0
encoding/json.(*decodeState).object(0xc42550e2d0, 0x5aa960, 0xc4254fd548, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc4305035a8 sp=0xc430503318
encoding/json.(*decodeState).value(0xc42550e2d0, 0x5aa960, 0xc4254fd548, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430503628 sp=0xc4305035a8
encoding/json.(*decodeState).unmarshal(0xc42550e2d0, 0x5aa960, 0xc4254fd548, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc4305036a0 sp=0xc430503628
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd548, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc4305036e8 sp=0xc4305036a0
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd530, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430503730 sp=0xc4305036e8
encoding/json.(*decodeState).object(0xc42550e1e0, 0x5aa960, 0xc4254fd530, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc4305039c0 sp=0xc430503730
encoding/json.(*decodeState).value(0xc42550e1e0, 0x5aa960, 0xc4254fd530, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430503a40 sp=0xc4305039c0
encoding/json.(*decodeState).unmarshal(0xc42550e1e0, 0x5aa960, 0xc4254fd530, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430503ab8 sp=0xc430503a40
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd530, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430503b00 sp=0xc430503ab8
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd518, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430503b48 sp=0xc430503b00
encoding/json.(*decodeState).object(0xc42550e0f0, 0x5aa960, 0xc4254fd518, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430503dd8 sp=0xc430503b48
encoding/json.(*decodeState).value(0xc42550e0f0, 0x5aa960, 0xc4254fd518, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430503e58 sp=0xc430503dd8
encoding/json.(*decodeState).unmarshal(0xc42550e0f0, 0x5aa960, 0xc4254fd518, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430503ed0 sp=0xc430503e58
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd518, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430503f18 sp=0xc430503ed0
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd500, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430503f60 sp=0xc430503f18
encoding/json.(*decodeState).object(0xc42550e000, 0x5aa960, 0xc4254fd500, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc4305041f0 sp=0xc430503f60
encoding/json.(*decodeState).value(0xc42550e000, 0x5aa960, 0xc4254fd500, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430504270 sp=0xc4305041f0
encoding/json.(*decodeState).unmarshal(0xc42550e000, 0x5aa960, 0xc4254fd500, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc4305042e8 sp=0xc430504270
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd500, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430504330 sp=0xc4305042e8
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd4e8, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430504378 sp=0xc430504330
encoding/json.(*decodeState).object(0xc42550def0, 0x5aa960, 0xc4254fd4e8, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430504608 sp=0xc430504378
encoding/json.(*decodeState).value(0xc42550def0, 0x5aa960, 0xc4254fd4e8, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430504688 sp=0xc430504608
encoding/json.(*decodeState).unmarshal(0xc42550def0, 0x5aa960, 0xc4254fd4e8, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430504700 sp=0xc430504688
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd4e8, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430504748 sp=0xc430504700
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd4d0, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430504790 sp=0xc430504748
encoding/json.(*decodeState).object(0xc42550de00, 0x5aa960, 0xc4254fd4d0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430504a20 sp=0xc430504790
encoding/json.(*decodeState).value(0xc42550de00, 0x5aa960, 0xc4254fd4d0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430504aa0 sp=0xc430504a20
encoding/json.(*decodeState).unmarshal(0xc42550de00, 0x5aa960, 0xc4254fd4d0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430504b18 sp=0xc430504aa0
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd4d0, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430504b60 sp=0xc430504b18
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd4b8, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430504ba8 sp=0xc430504b60
encoding/json.(*decodeState).object(0xc42550dd10, 0x5aa960, 0xc4254fd4b8, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430504e38 sp=0xc430504ba8
encoding/json.(*decodeState).value(0xc42550dd10, 0x5aa960, 0xc4254fd4b8, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc430504eb8 sp=0xc430504e38
encoding/json.(*decodeState).unmarshal(0xc42550dd10, 0x5aa960, 0xc4254fd4b8, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430504f30 sp=0xc430504eb8
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd4b8, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430504f78 sp=0xc430504f30
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd4a0, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc430504fc0 sp=0xc430504f78
encoding/json.(*decodeState).object(0xc42550dc20, 0x5aa960, 0xc4254fd4a0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:562 +0x1cb5 fp=0xc430505250 sp=0xc430504fc0
encoding/json.(*decodeState).value(0xc42550dc20, 0x5aa960, 0xc4254fd4a0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc4305052d0 sp=0xc430505250
encoding/json.(*decodeState).unmarshal(0xc42550dc20, 0x5aa960, 0xc4254fd4a0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc430505348 sp=0xc4305052d0
encoding/json.Unmarshal(0xc42008029c, 0x2, 0x4, 0x5aa960, 0xc4254fd4a0, 0x4, 0xc42008029c)
	/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc430505390 sp=0xc430505348
github.com/heidi-ann/ios/services.(*dummy).UnmarshalJSON(0xc4254fd488, 0xc42008029c, 0x2, 0x4, 0x0, 0x7f0d9dce8a78)
	/home/ubuntu/go/src/github.com/heidi-ann/ios/services/dummy.go:26 +0x6c fp=0xc4305053d8 sp=0xc430505390
...additional frames elided...

```

**Comment by dgryski** [comment]
Memory leak somewhere then and this is just a symptom?
