### ISSUE TITLE
concurrent map writes in window.go

### ISSUE THREAD

**Issue by heidi-ann** [heidi-ann/ios#18]
Bug found on OSX running the 3 server deployment from example3.conf with test clients.

```
fatal error: concurrent map writes

goroutine 51 [running]:
runtime.throw(0x28a3b0, 0x15)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820b175e0 sp=0xc820b175c8
runtime.mapassign1(0x1c60c0, 0xc82000a600, 0xc820b17748, 0xc820b1771e)
	/usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc820b17688 sp=0xc820b175e0
github.com/heidi-ann/ios/consensus.runMaster(0x0, 0xffffffffffffffff, 0x1, 0xc8200fc000, 0x0, 0x3, 0x186a0, 0x0, 0x64, 0x0, ...)
	/Users/heidi/go/src/github.com/heidi-ann/ios/consensus/master.go:145 +0xc6b fp=0xc820b17b50 sp=0xc820b17688
github.com/heidi-ann/ios/consensus.monitorMaster(0xc820094300, 0xc8200fc000, 0x0, 0x3, 0x186a0, 0x0, 0x64, 0x0, 0xa, 0x64, ...)
	/Users/heidi/go/src/github.com/heidi-ann/ios/consensus/master.go:14 +0x1cd fp=0xc820b17f20 sp=0xc820b17b50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820b17f28 sp=0xc820b17f20
created by github.com/heidi-ann/ios/consensus.Init
	/Users/heidi/go/src/github.com/heidi-ann/ios/consensus/consensus.go:62 +0x6b9

goroutine 1 [chan receive, 1 minutes]:
main.main()
	/Users/heidi/go/src/github.com/heidi-ann/ios/server/server.go:90 +0x11f3
```

I will look into it further now

**Comment by heidi-ann** [comment]
Fixed, however work is still required in consensus/window.go to correctly handle out of order requests
